### ISSUE TITLE
Media queries order broken in 5.0.2

### ISSUE THREAD

**Issue by fmal** [postcss/postcss-nested#102]
Seems like https://github.com/postcss/postcss-nested/commit/ec804d17bdeaf8c239abbf123dd5303dd07237a1 introduced some regression regarding @media blocks

Given the following piece of css:
```css
.main {
  @media mq-large-and-up {
    display: grid;
    grid-template-columns: 20rem 1fr;
    grid-template-areas: 'sidebar content';
  }

  @media mq-xlarge-and-up {
    grid-template-columns: 25rem 1fr;
  }
}
```

The `mq-xlarge-and-up` media query should come after `mq-large-and-up` in the output, but the result is this:

![Screenshot 2020-12-04 at 11 14 53](https://user-images.githubusercontent.com/927591/101151499-05430b80-3622-11eb-97a7-b9d30981f762.png)

Version 5.0.1 produced the correct order.

**Comment by ai** [comment]
Can you show input without any other PostCSS plugins?

**Comment by fmal** [comment]
@ai sure, i have replaced the CSS modules values variables from the original example to plain media queries and the same happens:

```css
.main {
  @media screen and (min-width: 48.75em) {
    display: grid;
    grid-template-columns: 20rem 1fr;
    grid-template-areas: 'sidebar content';
  }

  @media screen and (min-width: 88.5em) {
    grid-template-columns: 25rem 1fr;
  }
}
```

I have the following `postcss.config.json`:

```json
{
  "plugins": [
    "postcss-flexbugs-fixes",
    "postcss-nested",
    [
      "postcss-preset-env",
      {
        "autoprefixer": {
          "flexbox": "no-2009"
        },
        "stage": 3,
        "features": {
          "custom-properties": false
        }
      }
    ]
  ]
}
```

and using next.js as build tool but i'm not sure whether that's of any relevance

**Comment by ai** [comment]
I will try to look at this weekend

**Comment by ai** [comment]
```css
.main {
      @media screen and (min-width: 48.75em) {
        display: grid;
        grid-template-columns: 20rem 1fr;
        grid-template-areas: 'sidebar content';
      }

      @media screen and (min-width: 88.5em) {
        grid-template-columns: 25rem 1fr;
      }
    }
```

compiles to

```css
@media screen and (min-width: 48.75em) {
  .main {
    display: grid;
    grid-template-columns: 20rem 1fr;
    grid-template-areas: 'sidebar content'
  }
}
@media screen and (min-width: 88.5em) {
  .main {
    grid-template-columns: 25rem 1fr
  }
}
```

It looks correct.

Unfortunately, to fix this bug I will need CSS input, CSS output, and expected CSS output.

Try to reduce your PostCSS plugin and CSS until you will have the error. We will need a minimum example.

You can create a test repo if you will find a minimum example, which reproduce only on 2+ plugins (it could be a conflict between 2 plugins).
