### ISSUE TITLE
Wrong behaviour since version 5.0.2

### ISSUE THREAD

**Issue by jonnitto** [postcss/postcss-nested#107]
I use TailwindCSS. With version 5.0.1 I got with this code

```css
.apply {
  div {
    @apply fixed lg:static;
  }
}

.screen {
  @apply fixed;

  div {
    @screen lg {
      @apply static;
    }
  }
}
```
this CSS:
```css
.apply div {
    position: fixed;
}

.screen {
  position: fixed;
}

@media (min-width: 1024px) {
  .apply div {
    position: static;
  }

  .screen div {
    position: static
  }
}
```

but since 5.0.2 and up, I'll get this CSS:
```css
.apply div {
  position: fixed;
}

.screen {
  position: fixed
}

@media (min-width: 1024px) {

  .apply {
    div {
      position: static;
    }
  }

  div {
    position: static
  }
}
```
