### ISSUE TITLE
Moves @statements outside the CSS rule set

### ISSUE THREAD

**Issue by chaucerbao** [postcss/postcss-nested#11]
Input:
```css
.article {
  .title {
    @statement arguments;
    color: blue;
  }
}
```

Expected:
```css
.article .title {
  @statement arguments; /* Should stay inside ".article .title" rule set */
  color: blue;
}
```

Actual:
```css
.article .title {
  color: blue;
}
@statement arguments; /* Appears outside */
```

I see how this may be useful for @media queries, but for other PostCSS plugins, such as [postcss-simple-extend](https://github.com/davidtheclark/postcss-simple-extend) where the context is important, the @statement should stay inside.
