### ISSUE TITLE
`:global` not working as nested selector

### ISSUE THREAD

**Issue by arxpoetica** [postcss/postcss-nested#129]
I use `postcss-nested` with `postcss-global-nested`, putting nested before the global nested plugin (in order).

This works in v4+ of `postcss-nested` and v5.0.1 but not in `5.0.0` or `5.0.2+`.

Given:

```css
.selector {
	:global {
		h2 {
			color: pink;
		}
	}
}
```

Expected:
```css
.selector :global h2 {
	color: pink;
}
```

Actual:

```css
.selector :global {
	h2 {
		color: pink;
	}
}
```

It's a little baffling, because both `5.0.1` and `5.0.2` are putting out 

and 
```js
css: '.selector :global h2 {\n' +
    '\t\t\tcolor: pink;\n' +
    '\t\t}\n',
```

So... 🤷‍♂️

Happy to put together a repro if needed.

**Comment by ai** [comment]
What is Expected output?

**Comment by arxpoetica** [comment]
Sorry updated.

**Comment by arxpoetica** [comment]
Honestly, I think I'll need to create a repro. The behavior is really strange. I'll see if I can throw something together over the weekend.

**Comment by ai** [comment]
I never thought that it worked like this. Seems like it was non predicted feature.

Do you have reasons why it expected and should work?

**Comment by arxpoetica** [comment]
I'm a mess, lol. I STILL had it wrong above. I've fixed it (again), but for redundancy's sake, here's the correct again:

Expected:
```css
.selector :global h2 {
	color: pink;
}
```

Actual:

```css
.selector :global {
	h2 {
		color: pink;
	}
}
```

It's just not unfolding the nesting for anything past `:global`. There was another ticket about 3rd-level nestings, so it might be the same bug. I know this is working correctly on `5.0.1` but not on anything after.
