### ISSUE TITLE
Compatibility with `20lives/tailwindcss-rtl` plugin

### ISSUE THREAD

**Issue by bboro** [postcss/postcss-nested#133]
Thanks for the very useful plugin. We're currently using this on our installation and it works great. There's however one small problem we're noticing when we're trying to use this with `tailwindcss` + `tailwindcss-rtl` plugin.

Consider the following pcss:

```pcss
.element-a {
  .element-a-inner {
    .title {
      @apply ps-1;
    }
  }
}
```

This gets compiled into css:

```css
.element-a .element-a-inner [dir="rtl"] .title {
  padding-right: 0.25rem;
}

.element-a .element-a-inner [dir="ltr"] .title {
  padding-left: 0.25rem;
}
```

which is wrong as we add the `dir` attribute on our root `<html>` element, and that's also how the plugin states to do things. So the resulting CSS should ideally be:

```css
[dir="rtl"] .element-a .element-a-inner .title {
  padding-right: 0.25rem;
}

[dir="ltr"] .element-a .element-a-inner .title {
  padding-left: 0.25rem;
}
```

I've opened an [issue on tailwindcss-rtl plugin's repo](https://github.com/20lives/tailwindcss-rtl/issues/30) already, however they suggested to check with this plugin, so I'm trying my luck here. Honestly I'm not really sure where the core issue lies, or where to seek a fix for it. Thanks!
