### ISSUE TITLE
Unwrap media rules

### ISSUE THREAD

**Issue by nomadoda** [postcss/postcss-nested#141]
Given this input:

```css
@media screen {
  html {
    background-color: blue;
  }
  @media (min-width: 640px) {
    html {
      background-color: red;
    }
  }
}
```

The output is unchanged. I would like to unwrap the media rules, like so:

```css
@media screen {
  html {
    background-color: blue;
  }
}

@media screen and (min-width: 640px) {
  html {
    background-color: red;
  }
}
```

I've also tried without success to explicitly add media to the unwrap options, resulting in the following `.postcssrc` configuration:

```json
{
  "plugins": {
    "postcss-nested": { "unwrap": ["media"] }
  }
}
```

I know that nested media queries is valid css, but I'm struggling with IE11 which doesn't support it.

Using:
```
"postcss": "^8.3.11",
"postcss-nested": "^5.0.6",
```
