### ISSUE TITLE
disappeared rules

### ISSUE THREAD

**Issue by jney** [postcss/postcss-nested#15]
I've got the following css : 

````
button {
  background-color: #fff;
  border: 1px solid $green;
  font-size: 14px;
  margin-right: 128px;
  padding: 10px 20px;
  width: 128px;

  &:hover {
    background-color: $green;
    color: #fff;
  }

  &:active {
    background-color: $dark_grey;
    border-color: #fff;
    color: #fff;
  }
}
````
which is computed :

````
button{background-color:#fff;border:1px solid #85c401;font-size:14px;margin-right:120px;padding:10px 20px}button:active{background-color:#b3b3b3;color:#fff}
````

note the missing `:hover`.

changing it in a non nested way fix the issue.

**Comment by ai** [comment]
Very strange. I will look at it after PostCSS Plugin Guidelines.

**Comment by ai** [comment]
Do you use latest version of libary?

I atek your input and get this output:

```css
button {
  background-color: #fff;
  border: 1px solid $green;
  font-size: 14px;
  margin-right: 128px;
  padding: 10px 20px;
  width: 128px
}
button:hover {
  background-color: $green;
  color: #fff;
}
button:active {
  background-color: $dark_grey;
  border-color: #fff;
  color: #fff;
}
```
