### ISSUE TITLE
@at-root combined with & (ampersand)

### ISSUE THREAD

**Issue by davyrolink** [postcss/postcss-nested#150]
I encountered a problem when converting a Sass project to Postcss-nested.

SCSS input:
```css
.a {
    @at-root {
        .b & {
            color: lime;
        }
    }
}
```

Postcss-nested output:
```css
.b & {
    color: lime;
}
```

Expected (Sass) output:
```css
.b .a {
    color: lime;
}
```

I'm using the latest available version of Postcss-nested, 6.0.0
