### ISSUE TITLE
Ampersand class concat not working

### ISSUE THREAD

**Issue by projct1** [postcss/postcss-nested#154]
Hiho!
```css
.scrollable {
    overflow-x: auto;
    mask-image: linear-gradient(to right, white 90%, transparent);

    &--invert {
        mask-image: linear-gradient(to left, white 90%, transparent);
    }
}
```
Styles for `scrollable--inver` not applies. Its excepted or...?
My `postcss.config.js`:
```javascript
module.exports = {
  plugins: {
      'postcss-import': {},
      'tailwindcss/nesting': 'postcss-nesting',
      tailwindcss: {},
      autoprefixer: {},
  },
}
```
I use `vite` as bundler.

**Comment by ai** [comment]
What is CSS output?

**Comment by projct1** [comment]
```css
.scrollable {
    overflow-x: auto;
    -webkit-mask-image: linear-gradient(to right, white 90%, transparent);
    mask-image: linear-gradient(to right, white 90%, transparent)
}

--invert.scrollable {
    -webkit-mask-image: linear-gradient(to left, white 90%, transparent);
    mask-image: linear-gradient(to left, white 90%, transparent)
}
```
