### ISSUE TITLE
Nesting with ampersand

### ISSUE THREAD

**Issue by JamyGolden** [postcss/postcss-nested#161]
Hello @ai  :wave: I've been having issues nesting with a selector including ampersand, for example:

```css
.a {
    color: red;

    .b + & {
        color: blue;
    }
}
```
I would expect this to convert to: `.b + .a`. I understand that while the postcss selector is nested, the output selector doesn't begin with a `.a`. I feel like this used to work this way? Or at least Sass worked/worked this way. 

Is this functionality intentional or should it work as I mentioned?
