### ISSUE TITLE
7.0.0 broke comments on nested elements

### ISSUE THREAD

**Issue by pgorny** [postcss/postcss-nested#164]
The change in #163 naively that was included in 7.0.0 expects the node contents to be something that can be included in a regex, but the problem is that both CSS and Regex share some syntax elements, including `[]` used for attribute selector and character classes, respectively.

This means that a simple code like this:

```css
/* Comment */
&[data-roots-all] {
  display: none;
}
```

will now fail with 
```
SyntaxError: Invalid regular expression: //* Comment */ *
*&[data-roots-all] {
   display: none;
}/: Range out of order in character class
```

This is due to the fact that `[data-roots-all]` is not treated as a literal, but rather a  character class - and thus `s-a` class trips it up.

**Comment by ai** [comment]
@Ulyanov-programmer can you look and fix?

**Comment by Ulyanov-programmer** [comment]
I'll get on it as soon as possible. It will be necessary to add similar situations to the tests...

**Comment by Plumbiu** [comment]
It seems that comments cause a lot of problems:

```css
.md {
  color: red;
  & > * {
    margin-bottom: 12px;
  }
  /* table */
  table {}
}
```

generated:

```css
.md {
  color: red;
}
  .md .md * {
    margin-bottom: 12px;
  }
  /* table */
  table {
  }
```
