### ISSUE TITLE
Unexpected nested rule in parent

### ISSUE THREAD

**Issue by Xaviju** [postcss/postcss-nested#17]
Current code
```css
.scrum {
    .explanation {
        padding: 5rem;
    }
}
```

Unexpected result
```css
.scrum{
        padding:80px;
}
.scrum .explanation{
    padding:80px;
}
```

Using last version of postcss-nested ("postcss-nested": "^0.3.1")

Any ideas why this is happening?

**Comment by ai** [comment]
My output is:

```css
.scrum .explanation {
    padding: 5rem;
}
```

Can you try to look at other environment?
