### ISSUE TITLE
Expose & as a comma separated list of space separated values

### ISSUE THREAD

**Issue by Grawl** [postcss/postcss-nested#22]
It would be much awesome to manupulate with `&` like this:

```css
.foo, .bar > a { first: &[1]; second-combinator: &[2][2] }
```

to generate this:

```css
.foo, .bar > a { first: ".foo"; second-combinator: ">"}
```

got this idea at @chriseppstein's [answer](https://github.com/less/less.js/issues/1075#issuecomment-16891103) in less/less.js#1075

With this, we will can specify `:hover` target on right selector, for example,

input:

```css
.foo {
  .bar {
    color: gray;
    &[2]:hover &[1] {
      color: blue;
      }
    }
  }
```

output:

```css
.foo .bar{
  color: gray;
  }
.foo:hover .bar {
  color: blue;
  }
```
