### ISSUE TITLE
node-pixrem not working properly with nested rules

### ISSUE THREAD

**Issue by meritt** [postcss/postcss-nested#25]
**Input source**

```css
body {
  font-size: 1.4rem;
  line-height: 1.2em;
}

dd {
  margin-left: 0;
  padding-left: 1.75rem;

  & + dt {
    margin-top: 2rem;
  }
}
```

**Output**

```css
body {
  font-size: 22px;
  font-size: 1.4rem;
  line-height: 1.2em;
}

dd {
>>    margin-top: 32px;
  margin-left: 0;
  padding-left: 28px;
  padding-left: 1.75rem;
}

dd + dt {
  margin-top: 32px;
  margin-top: 2rem;
}
```

[Example of configuration](https://github.com/meritt/postcss-bugs/tree/rem-with-nested)
