### ISSUE TITLE
Wrong parsing of nested elements

### ISSUE THREAD

**Issue by Icewild** [postcss/postcss-nested#31]
Hello. 
I found that this plugin works incorrect. In your example there is a mistake and if you run this code as is, in result css-file you'll get only last nested element. So if you want to work this properly you need to separate nested elements with commas. It would be awesome if you could fix this and make this plugin work like SASS and your example, i mean without commas.

```
.phone {
    &_title {
        width: 500px;
        @media (max-width: 500px) {
            width: auto;
        }
        body.is_dark & {
            color: white;
        }
    }
    img {
        display: block;
    }
}

```

Result of this is:

```
.phone img {
  display: block;
}
```

**Comment by ai** [comment]
Can you write what input you want to have?

**Comment by Icewild** [comment]
I'm waiting to get next result:

```
.phone_title {
    width: 500px;
}
@media (max-width: 500px) {
    .phone_title {
        width: auto;
    }
}
body.is_dark .phone_title {
    color: white;
}
.phone img {
    display: block;
}
```

**Comment by ai** [comment]
I tested you CSS on CodePen and on input:

```css
.phone {
    &_title {
        width: 500px;
        @media (max-width: 500px) {
            width: auto;
        }
        body.is_dark & {
            color: white;
        }
    }
    img {
        display: block;
    }
}
```

I got:

```css
.phone_title {
    width: 500px;
}
@media (max-width: 500px) {
    .phone_title {
        width: auto;
    }
}
body.is_dark .phone_title {
    color: white;
}
.phone img {
    display: block;
}
```
