### ISSUE TITLE
Please add support for @apply rule

### ISSUE THREAD

**Issue by JosefJezek** [postcss/postcss-nested#32]
Could you add support for CSS `@apply` Rule?

http://tabatkins.github.io/specs/css-apply-rule/
https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins
https://github.com/StartPolymer/polymer-starter-kit-plus

Issue 1

```css
.Navigation {
  --paper-menu-selected-item: {
    color: var(--default-primary-color);
  };
}
```

->  

```css
.Navigation --paper-menu-selected-item: {
  color: var(--default-primary-color);
}
```

Issue 2

```css
.Main {
&-content {
   @media (--sm-viewport) {
      @apply(--paper-font-body);
    }
}
}
```

->

```css
@media (max-width: 599px) {
  @apply(--paper-font-body);
}
```

Thank you

**Comment by JosefJezek** [comment]
@ai How to resolve this issues? Please

**Comment by ai** [comment]
@JosefJezek problem is not with code, but with logic. Seems like `apply` syntax just incompatible with postcss-nested logic.

Maybe you should use [postcss-nesting](https://github.com/jonathantneal/postcss-nesting) plugin, because it is based on same Tabatkins purpose. Or use postcss-extend or postcss-mixins instead of apply (because right now there is no really benefits of apply spec)

**Comment by JosefJezek** [comment]
Apply rule is used in Polymer. I need solution for this rule.

**Comment by ai** [comment]
1. Other plugin postcss-nesting
2. PR (this plugin is only 80 lines of plain JS code)
3. Wait end of my vacation

Sorry, I really have no option to help you, because right now I spend all my time to fight with Shengen fingerprint bureaucracy (by some reason system do not take my fingerprint and ban any possibility to visit Europe).

**Comment by JosefJezek** [comment]
1. `Error: no writecb in Transform class` :-(

**Comment by TrySound** [comment]
@JosefJezek Show code

**Comment by ai** [comment]
Poke @jonathantneal

**Comment by JosefJezek** [comment]
`postcss-nesting` write error for this css

```css
.Main {
  background: var(--primary-background-color);

  @nest &-content {
    color: var(--primary-text-color);
    @media (max-width: 599px) {
      @apply(--paper-font-body);
    }
    @media (min-width: 600px) {
      @apply(--paper-font-body2);
      padding: 48px 62px;
    }
  }
}
```

**Comment by JosefJezek** [comment]
I am working now on https://github.com/StartPolymer/polymer-starter-kit-plus

I need postcss-nested or postcss-nesting for SUIT CSS. Please help me.

https://suitcss.github.io/

**Comment by ai** [comment]
@JosefJezek `postcss-nesting` uses 2 `{{` to mark indent according Tabatkin's spec. Not one `{` as Sass.

@jonathantneal I told you, that users will miss `{{` from current postcss-nesting docs ;-)

**Comment by ai** [comment]
@JosefJezek the main problem, why I can't help you is that seems like Sass nesting is incompatible with `@apply` spec. Look to first issue: how I can detect that you do not want bubbling that custom selector?

**Comment by ai** [comment]
@JosefJezek can you explain what output is expected in both cases? And do you use postcss-apply for `@apply` mixin

**Comment by ai** [comment]
Anyway, main benefits of postcss-nesting is that double `{{`, so you can mark manually what rules should be bubbled.

**Comment by JosefJezek** [comment]
I fix `{{` for postcss-nesting and result is :-(

```css
@media (max-width: 599px) {

  @apply(--paper-font-body);
}
@media (min-width: 600px) {

  @apply(--paper-font-body2);
  padding:         48px 62px;
}
```

**Comment by JosefJezek** [comment]
Polymer elements using `@apply` rule. This rule is implemented using JS in Polymer. I need using this rule for developing. `postcss-apply` is good for final transform after vulcanize of all polymer elements.

https://github.com/polymer/vulcanize

https://github.com/PolymerElements/paper-menu/blob/master/paper-menu.html#L77

**Comment by jonathantneal** [comment]
Just a quick clarification, the spec for CSS Nesting will leverage `@nest` at-rules. This will make the experience consistent with nested `@media`.

```css
/* before */

a, b {
    color: red;

    @nest c, d {
        color: white;

    @nest & & {
        color: blue;
    }

    @nest &:hover {
        color: black;
    }

    @media (min-width: 30em) {
        color: yellow;
    }
}

/* after */

a, b {
    color: red;
}

a c, b c, a d, b d {
    color: white;
}

a a, a b, b a, b b {
    color: blue;
}

a:hover, b:hover {
    color: black;
}

@media (min-width: 30em) {
    a, b {
        color: yellow;
    }
}
```

**Comment by ai** [comment]
@JosefJezek yeap, you should use `postcss-nesting`, because `@apply` is incompatible with postcss-nested and Sass. There is now way, how I can be sure, that I can’t bubble `--paper-menu-selected-item:` (because `--` is normal in other spec and trailing `:` uses in different plugins). So you should tell manually what rules should be bubbled.

@tabatkins maybe you can suggest some way to fix it?

**Comment by ai** [comment]
@JosefJezek please create issue in `postcss-nesting`, @jonathantneal will help you there. Sorry, if you have some solution, I can write code, but seems like it is just API conflict and I can’t fix anything without broke other specs or plugins.

As third solution you can fork my plugin and fix them specially for `@apply`. Like `postcss-nested-apply`. You need just block bubbling `rule.selector.startsWith('--')`.

**Comment by ai** [comment]
I create a task for second issue #33, but anyway first issue block using `postcss-nested` with `@apply`

**Comment by tabatkins** [comment]
I don't understand the problem.  What's incompatible between @apply and nesting?  @apply is just another application of custom properties; whatever difficulties y'all have with var() today, you'll have with @apply, and whatever solution y'all use to deal with var() will apply to @apply as well.

**Comment by ai** [comment]
@tabatkins problem is here:

```css
.Navigation {
  --paper-menu-selected-item: {
    color: var(--default-primary-color);
  };
}
```

`--paper-menu-selected-item` looks like nested selector and postcss-nested (and Sass, as I understand) will bubble it to `.Navigation --paper-menu-selected-item:`.

The problem is because variable can be a selector.

**Comment by tabatkins** [comment]
Oh, if that syntax is allowed in PostCSS's nesting, then yeah, it's incompatible.  That's a problem for y'all to sort out, because that's double-wrong per CSS - direct nesting requires you to start the selector with an `&`, and the only valid use of a naked `--foo` in a selector like that would be a type selector for a custom element with a weird name.

Tho, a naked : without an ident after it makes an invalid selector.  You should be able to distinguish based on that.

**Comment by ai** [comment]
@tabatkins do I understand that only custom properties can be started from `--`? Is it in current CSS (so it will not be changed)?

**Comment by jonathantneal** [comment]
This repository, `postcss-nested`, uses Sass-style nesting. My repository, `postcss-nesting`, uses the syntax you clarified for me yesterday, @tabatkins. It’s perhaps a little confusing.

**Comment by tabatkins** [comment]
@ai: Yes, custom properties start with `--`. Lots of other "custom" things do too, like custom pseudo-classes (which are like `:--foo`), etc.  It won't be changed.  (Note that @apply just relies on ordinary custom properties.)

@jonathantneal: Ah, I am indeed confused.

**Comment by ai** [comment]
@tabatkins this is why I can’t block bubbling selectors started from `--`, they can be used in many other ways.

Maybe we can think to fix this case in spec? In PostCSS user can switch nesting syntax, but Sass users seems will be in same trap.

@jonathantneal what will be on “issue 2” in postcss-nesting.

**Comment by tabatkins** [comment]
@ai: No, every way is distinguishable.  The only way that a selector can start with `--foo` is if you have a custom element with a name like `<--foo>`, and I'm not even certain that's legal.

**Comment by jonathantneal** [comment]
I tested the following code using the PostCSS **nesting**, **custom-selectors**, **custom-media**, **custom-properties**, **media-minmax**, and **apply** plugins:

```css
@custom-media --sm-viewport (width < 30em);
@custom-selector :--content -body;

:root {
	--paper-font: paper, sans-serif;
	--paper-font-body: {
		color: green;
		font-family: var(--paper-font);
	};
}

.main {
	@nest &:--content {
		@media (--sm-viewport) {
			@apply --paper-font-body;
		}
	}
}
```

And the result was:

```css
@media (max-width: 29.999em) {
	.main-body {
		color: green;
		font-family: paper, sans-serif;
	}
}
```

Does this fulfill your expectations, @JosefJezek? Save for the `max-width` guesstimation, is this the appropriate equivalent, @tabatkins?

**Comment by ai** [comment]
@jonathantneal problem is that @JosefJezek do not use `postcss-apply`. `@apply` will be executed by Polymer. So you should test it without `postcss-apply`.

**Comment by jonathantneal** [comment]
Without the **apply** plugin, I got this:

```css
:root {
	--paper-font-body: {
		color: green;
		font-family: paper, sans-serif;
	};
}

@media (max-width: 29.999em) {
	.main p {
		@apply --paper-font-body;;
	}
}
```

**Comment by ai** [comment]
@jonathantneal awesome

@JosefJezek seems like everything will work with `postcss-nested`. See this example: https://github.com/postcss/postcss-nested/issues/32#issuecomment-140845254

**Comment by JosefJezek** [comment]
@ai @jonathantneal `@custom-selector` is hack which is not ideal for SUIT CSS, example component `Main`

```css
/** @define Main */

.Main {
  background: var(--primary-background-color);

  &-content {
    color: var(--primary-text-color);
    @media (--sm-viewport) {
      @apply(--paper-font-body);
    }
    @media (--md-viewport) {
      @apply(--paper-font-body2);
      padding: 48px 62px;
    }
  }

  &-headerMiddleContent  {
    height: 100%;
    margin-left: 48px;
  }

  &-header:not(.tall) &-headerMiddleContent {
    font-size: 18px;
    padding-bottom: 0;
  }

  &-headerBottomContent {
    margin-left: 48px;
    /* Required for main area's paper-scroll-header-panel custom condensing transformation */
    transform-origin: left center;
  }

  &-headerTitle {
    @apply(--paper-font-display2);
    /* Required for main area's paper-scroll-header-panel custom condensing transformation */
    transform-origin: left center;
    @media (--sm-viewport) {
      @apply(--paper-font-headline);
    }
  }

  &-headerSubTitle {
    @apply(--paper-font-subhead);
  }
}
```
