### ISSUE TITLE
Conflict with postcss-nested and postcss-extend

### ISSUE THREAD

**Issue by Dylan-Chapman** [postcss/postcss-nested#35]
I'm trying to extend from within a nested selector. I can't quite figure out how to get everything working.

Input:

```css
@import "silent-placeholders.css";

%inline-placeholder {
    content: "test";
}

.test {
    color: red;

    &:before {
        @extend %inline-placeholder;
    }
}
```

If postcss-extend is included first and postcss-nested is included after, the output is:

```css
&:before {
    content: "test";
}

.test {
    color: red;
}
```

If postcss-nested is included first and postcss-extend is included after, %silent-placeholders from silent-placeholders.css (for use with postcss-extend) are copied into the CSS output. Is there a way to not have these silent placeholders in the output?
