### ISSUE TITLE
At-rule fro example moves too up

### ISSUE THREAD

**Issue by ai** [postcss/postcss-nested#4]
``` css
.phone {
  &_title {
    width: 500px;
    @media (max-width: 500px) {
      width: auto;
    }
  }
  body.is_dark &_title {
    color: white;
  }
  img {
    display: block;
  }
}
```

compiles to:

``` css
    @media (max-width: 500px) {
    .phone_title {
      width: auto
  }
    }.phone_title {
    width: 500px
  }
  body.is_dark .phone_title {
    color: white;
  }
  .phone img {
    display: block;
  }
```
