### ISSUE TITLE
Composing from nested parent selector

### ISSUE THREAD

**Issue by sunny-g** [postcss/postcss-nested#45]
It would be nice if this plugin would support `compose`ing from the current selector's parent, especially if the parent selector is not used in the markup and instead exists for namespacing.

Example:
```css
.button {
  background-size: 20px;

  &--opened {
    composes: &; /* doesnt work */
    background-image: svg-load(...);
  }

  &--closed {
    composes: &; /* doesnt work */
    background-image: svg-load(...);
  }
}
```
```js
<div
  className={isOpen
    ? styles['button--opened']
    : styles['button--closed']
  }
/>

```

Currently, when you attempt to do this, this is the error you get:
```sh
ERROR in ./~/css-loader?modules&sourceMap&importLoaders=1&localIdentName=[local]___[hash:base64:5]!./~/postcss-loader!./widgets/static/widgets/ImageryBrowser/Filterer.styles.css
Module build failed: referenced class name "&" in composes not found (73:16)
```

I assume that to be a problem with this library, not css-modules but I could be mistaken.
