### ISSUE TITLE
Is it possible not to uglify child css rules

### ISSUE THREAD

**Issue by redguardtoo** [postcss/postcss-nested#46]
react js code (please note `dropdown` div is generated by 3rd party component which I can't change):

```javascript
import st from './MyComp.css'>
<div className={st.Header}>
   <div className="dropdown">
   </div>
</div>
```

MyComp.css:
```css
.rightside-top {
  .dropdown {
     float:right;
  }
}
```

It's compiled into `.Header__rightside_top .Header__dropdown__YBZuA {float:right;}` but I don't want to compile `.dropdown` into `.Header__dropdown__YBZuA`. How can I do that?
