### ISSUE TITLE
Impossible to write closest children :global selector

### ISSUE THREAD

**Issue by inferusvv** [postcss/postcss-nested#47]
Next examples are not working:

```
.example1 {
  :global {
    > .mdl-progress {
      background: #fff;
    }
  }
}

.example2 {
  > :global {
    .mdl-progress {
      background: #fff;
    }
  }
}
```

**Comment by ai** [comment]
Output of this input looks like good for me:

```css
.example1 :global > .mdl-progress {
    background: #fff;
}

.example2 > :global .mdl-progress {
    background: #fff;
}
```

What problem do you have with this input example?
