### ISSUE TITLE
Better support for custom at-rules

### ISSUE THREAD

**Issue by ZeeCoder** [postcss/postcss-nested#50]
Sass handles custom at-rules the same way it handles @media queries.

This
```css
.container {
  @define-container;
  font-size: 10px;
  background: green;
  
  @media (min-width: 500px) {
    background: red;
  }
  
  @container (width >= 200px) {
    font-size: 20px;
  }
}
```
Becomes this:

```css
.container {
  @define-container;
  font-size: 10px;
  background: green;
}
@media (min-width: 500px) {
  .container {
    background: red;
  }
}
@container (width >= 200px) {
  .container {
    font-size: 20px;
  }
}
```

The above is the syntax my @container query project would benefit from a lot: https://github.com/ZeeCoder/container-query

Not sure how hard would this be to implement, given some directions I would look into it myself. 👍
