### ISSUE TITLE
Allow escaping of ampersand in attribute selectors

### ISSUE THREAD

**Issue by NeonPaul** [postcss/postcss-nested#55]
I want to be able to write a rule like this:

```css
.my-room {
  &[data-category='Sound & Vision'] {
    color: $electric-blue;
  }
}
```

Currently  the second `&` is replaced with the current selector.

Please either add the option to escape an ampersand or automatically ignore them in attribute selectors.
