### ISSUE TITLE
Cannot handle chained css

### ISSUE THREAD

**Issue by DominicTobias** [postcss/postcss-nested#65]
Hi,

Thanks for this plugin. I noticed it doesn't handled chained CSS though:

```css
.myclass {
  &-something1.&-something2 {
    background-color: blue;
  }
}
```

In this codepen demo the background should be blue but the second selector won't work:

https://codepen.io/ferahl/pen/VzrqeM
