### ISSUE TITLE
Update Example to Use Less-Style Nested Blocks

### ISSUE THREAD

**Issue by KenPowers** [postcss/postcss-nested#7]
Turns out the way `postcss-nested` is written it supports Less-style nested blocks.

For example, this example from the README:

```css
.phone {
    &_title {
        width: 500px;
        @media (max-width: 500px) {
            width: auto;
        }
    }
    body.is_dark &_title {
        color: white;
    }
    img {
        display: block;
    }
}
```

Still works if we do this:

```css
.phone {
    &_title {
        width: 500px;
        @media (max-width: 500px) {
            width: auto;
        }
        body.is_dark & {
            color: white;
        }
    }
    img {
        display: block;
    }
}
```

They both compile down to:

```css
.phone_title {
    width: 500px;
}
@media (max-width: 500px) {
    .phone_title {
        width: auto;
    }
}
body.is_dark .phone_title {
    color: white;
}
.phone img {
    display: block;
}
```

With the exception that the example in the README says `phone_title` instead of `.phone_title` for the second instance of `&_title` (this is a typo I believe, unless I ran `postcss` incorrectly).

The reason I say Less-style is because last time I tried Sass/Scss didn't support this. But I just tried it in SassMeister and it seems like it works flawlessly there as well:

![image](https://cloud.githubusercontent.com/assets/174864/6066819/14e8d830-ad3e-11e4-8f54-8242eaa5d43e.png)

The advantage of `body.is_dark &` vs `body.is_dark &_title` is less repetition.
