### ISSUE TITLE
@page at-rule could be allowed to nest

### ISSUE THREAD

**Issue by niksajanjic** [postcss/postcss-nested#75]
https://developer.mozilla.org/en-US/docs/Web/CSS/%40page
https://www.w3.org/TR/css3-page/#using-named-pages

Is it possible to allow nesting for `@page` at-rule. Right now we have to write the rule like this:
```css
@page {
  padding: 20px;
}

@page:first {
  padding: 10px;
}
```

It would be nice to allow us to write:
```css
@page {
  padding: 20px;

  &:first {
    padding: 10px;
  }
}
```

Same goes with named @page at-rules:
```css
@page report {
  padding: 20px;

  &:first {
    padding: 10px;
  }
}
```
Unfortunatelly, I can see an issue arrising with this example though:
```css
@page {
  @top {
    padding: 20px;
  }
}

@page:first {
  @top {
    padding: 10px;
  }
}
```

Nested rules could be written something like this:
```css
@page {
  @top {
    padding: 20px;
  }

  &:first {
    @top {
      padding: 10px;
    }
  }
}
```

So this might not be that straigthforward feature to implement. Just trying to start a discussion if this feature makes sense.
