### ISSUE TITLE
:host selector nesting does not work as expected

### ISSUE THREAD

**Issue by benjamind** [postcss/postcss-nested#79]
Currently if you do this:

```css
:host {
    &:hover {
        background-color: red;
    }
}
```

Results in:

```css
:host:hover {
    background-color: red;
}
```

Which is invalid, what it should output is:

```css
:host(:hover) {
    background-color: red;
}
```

**Comment by ai** [comment]
Use

```css
:host {
    &(:hover) {
        background-color: red;
    }
}
```

I can't make `&:host` hack, since it will not be predictable.

**Comment by benjamind** [comment]
Actually you may need to reopen this.

In testing using:

```css
:host {
    &(:hover) {
        background-color: red;
    }
}
```

Results in only this:

```css
:host {
    background-color: red;
}
```
