### ISSUE TITLE
Bubbling not working as expected

### ISSUE THREAD

**Issue by Windvis** [postcss/postcss-nested#81]
Hey there!

I'm experimenting with a new PostCSS setup based on postcss-nested and [Tailwind](https://tailwindcss.com).

Tailwind has a set of @rules which I want to let play nice with postcss-nested. More specifically the [@screen](https://tailwindcss.com/docs/functions-and-directives#screen) and [@variants](https://tailwindcss.com/docs/functions-and-directives#variants) rules.

I added both to the `bubble` option of postcss-nested.

I'm trying to transform the following code:
```css
.dummy-component {
  @apply p-8 rounded shadow bg-white border;

  &__content {
    @apply font-thin font-sans text-5xl text-center;
  }

  @screen xl {
    @apply w-1/3; /* This doesn't work */
    width: calc(100% / 3); /* This does */
  }

  /* @media behaves exactly the same  */
  @media (min-width: 768px) {
    @apply w-1/2; /* This doesn't work */
    width: 50%; /* This does */
  }

  @variants hover {
    @apply border-green;
    border-color: lime;
  }
}
```

And this is the result (before Tailwind does its thing):
```css
.dummy-component {
  @apply p-8 rounded shadow bg-white border;
}
.dummy-component__content {
  @apply font-thin font-sans text-5xl text-center;
}
@screen xl {
  .dummy-component {
    /* This doesn't work */
    width: calc(100% / 3); /* This does */
  }
  @apply w-1/3;
}
/* @media behaves exactly the same  */
@media (min-width: 768px) {
  .dummy-component {
    /* This doesn't work */
    width: 50%; /* This does */
  }
  @apply w-1/2;
}
@variants hover {
  .dummy-component {
    border-color: lime;
  }
  @apply border-green;
}
```

The @apply rules (which Tailwind uses to "mixin" styles) don't get nested in the bubbled selector as classic css rules do.

Any idea what could be causing this?

**Comment by ai** [comment]
Maybe this option will help you

https://github.com/postcss/postcss-nested#bubble

**Comment by Windvis** [comment]
No, that's what I'm using at the moment. The problem seems to be that at-rules children won't we bubbled. It seems to be coded that way.

**Comment by ai** [comment]
OK. Can you show the expected output?

Sorry, CSS example is too long, it is hard to me to understand it.

**Comment by Windvis** [comment]
Yea sure, sorry!

Input:
```css
.class {
  @screen xl {
    @apply w-1/3; /* I want this to behave like a normal css rule */
    width: calc(100% / 3); /* Like this */
  }
}
```

expected output:
```css
@screen xl {
  .class {
    @apply w-1/3;
    width: calc(100% / 3);
  }
}
```

actual output:
```css
@screen xl {
  .class {
    width: calc(100% / 3);
  }
  @apply w-1/3; /* It doesn't get nested inside the selector */
}
```
