### ISSUE TITLE
Incorrect spacing of compiled CSS

### ISSUE THREAD

**Issue by mccoyrjm** [postcss/postcss-nested#85]
Writing a basic parent-child selector like this
```css
.class1 {
  .class2 {
    property: value;
  }
}
```
results in an incorrect format on the compiled CSS in lines 2 & 3. Those lines are using the spacing from lines 2 & 4 from the Pre-Compiled code.
```css
.class1 .class2 {
    property: value; /* 4 spaces before */
  } /* 2 spaces before */
```
Per the documentation, I'd expect line 2 to have 2 spaces before and line 3 to have none.

Here is a link to a [codepen ](https://codepen.io/mccoyrjm/pen/BaBKpKx) using the **postcss-nested** plugin demonstrating this behavior. 

**Steps to Replicate**
1. On a new Codepen, pick **PostCSS** as the CSS Pre-Processor.
2. Add `postcss-nested` plugin.
3. Write PostCSS as described earlier.
4. Select **View Compiled CSS**
